#!/usr/bin/env bash

packer="packer.lua"
output="./README.md"
packages_list='packages.temp'
start_text="|---|---|"
end_text="<!--end autogenerated table-->"

packages="$(
	rg '.*("([a-zA-Z0-9-_]+/[.a-zA-Z0-9-_]+)").*' \
		--glob="$packer" \
		--replace='$2' \
		--no-line-number \
		--no-filename | sort -uf
)"

sed -i "/$start_text/,/$end_text/{//!d;};" "$output"

printf "\
=====  Getting description for each package  =====\n\
      =====  this might take a while  =====\n"

while LF='' read -r line; do
	description="$(gh repo view "$line" --json description --jq .description)"

	printf "|[%s](https://github.com/%s)|%s|\n" "$line" "$line" "$description" >>"$packages_list"
done <<<"$packages"

sed -i "/$start_text/ r $packages_list" "$output"

rm "$packages_list"

echo "󱓟 README updated 󱪚 "
