--- @meta

--- @alias What
---| "fg"    foreground color (GUI: color name used to set the color, cterm: color number as string, term: empty string)
---| "bg"    background color (as with "fg")
---| "font"    font name (only available in the GUI) |highlight-font|
---| "sp"    special color (as with "fg") |guisp|
---| "fg#"    like "fg", but for the GUI and the GUI is running the name in "#RRGGBB" form
---| "bg#"    like "fg#" for "bg"
---| "sp#"    like "fg#" for "sp"
---| "bold"    "1" if bold
---| "italic"  "1" if italic
---| "reverse"  "1" if reverse
---| "inverse"  "1" if inverse (= reverse)
---| "standout"  "1" if standout
---| "underline"  "1" if underlined
---| "undercurl"  "1" if undercurled
---| "underdouble"  "1" if double underlined
---| "underdotted"  "1" if dotted underlined
---| "underdashed"  "1" if dashed underlined
---| "strikethrough"  "1" if struckthrough
---| "altfont"  "1" if alternative font
---| "nocombine"  "1" if nocombine

--- @alias E {bufnr:integer, col:integer, lnum:integer, text:string, type:string, valid:integer}
