require("config.options")
require("config.autocmds")
require("config.commands")
require("config.keymaps")
require("config.lsp")
require("config.incremental_selection").setup()
require("config.terminal").setup()
require("plugins")
