local Util = require("config.util")

local nmap = Util.nmap

local function act_center(lhs)
	nmap(lhs, function()
		Util.feedkeys(lhs)
		Util.scroll_center()
	end, { desc = "Center screen after " .. lhs })
end
local function center_act(lhs)
	nmap(lhs, function()
		Util.scroll_center()
		Util.feedkeys(lhs)
	end, { desc = "Center screen before " .. lhs })
end

act_center("(")
act_center(")")
act_center("G")
act_center("N")
act_center("n")
act_center("zj")
act_center("zk")
act_center("zx")
act_center("{")
act_center("}")
act_center("zn")
act_center("zm")

center_act("<C-d>")
center_act("<C-u>")
center_act("A")
center_act("a")
center_act("I")
center_act("i")
center_act("O")
center_act("o")
center_act("S")
center_act("s")

nmap("c", "zzzvc", { desc = "Center screen before c" })
nmap("C", "zzzvC", { desc = "Center screen before C" })
nmap("za", "zazz", { desc = "Center screen after toggling a fold" })
nmap("zA", "zAzz", { desc = "Center screen after toggling a fold recursively" })
