---
on: [push]
jobs:
  CSPELL:
    name: cSpell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: streetsidesoftware/cspell-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          incremental_files_only: false
