on:
  push:
    branches:
      - main
  pull_request:
jobs:
  LUACHECK:
    name: Luacheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install luacheck
        run: |
          echo "Installing luacheck..."
          sudo apt update
          sudo apt install luarocks
          sudo luarocks install luacheck
      - name: Lint
        run: |
          echo "Linting with luacheck"
          luacheck .
